dbfilename redis_queue.rdb
dir /home/wahyu260697/document/Erpnext/silverplast/frappe-bench/config/pids
pidfile /home/wahyu260697/document/Erpnext/silverplast/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/wahyu260697/document/Erpnext/silverplast/frappe-bench/config/redis_queue.acl
